import { Ref, getModelForClass, prop } from '@typegoose/typegoose';
import { User } from 'app/users/model/User';
import { ObjectId } from 'mongodb';

class UserReferral {
  // ObjectId generated by mongodb
  @prop()
  public id!: ObjectId;
  /**
   * @param  referralId - The referral id of the owner
   */
  @prop()
  public referralId!: string;
  /**
   * The @owner is a person one who refer his friend
   */
  @prop()
  public owner!: Ref<User>;
  /**
   * @param user - is a person one who referred by his friend
   */
  @prop()
  public user!: Ref<User>;
  /**
   * @param madeFirstTransaction - The referral is completed once the user made his first transaction
   */
  @prop()
  public madeFirstTransaction!: boolean;
}

const ReferralUserModel = getModelForClass(UserReferral, {
  schemaOptions: {
    collection: 'referrals',
    versionKey: false,
    timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt' },
  },
});

export { UserReferral, ReferralUserModel };
